# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-10 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
