# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-17 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0003_auto_20181010_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='rank',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='profile',
            name='gamertag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
