# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-18 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0009_auto_20181018_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_games',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
