# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-18 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0010_profile_favorite_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_interests',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
