# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0011_profile_current_interests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('host', models.CharField(max_length=20)),
                ('game', models.CharField(max_length=20)),
                ('tournament_type', models.CharField(max_length=20)),
                ('size', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
