# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-25 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0013_auto_20181025_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='host',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_type',
            field=models.CharField(max_length=40),
        ),
    ]
