# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-27 06:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0023_auto_20181027_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='endTime',
        ),
    ]
