# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-27 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0025_auto_20181027_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='startTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
