# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0026_auto_20181027_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='startTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
