# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-27 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0027_auto_20181027_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='startDay',
            field=models.CharField(default=datetime.datetime(2018, 10, 27, 20, 9, 40, 311973, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='startTime',
            field=models.CharField(max_length=7),
        ),
    ]
