# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-08 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0029_auto_20181027_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newMessages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='newNotifications',
            field=models.BooleanField(default=False),
        ),
    ]
