# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-13 23:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UrTourn', '0030_socialmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 11, 13, 23, 55, 5, 191774, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
