# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-09 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0030_auto_20181108_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='newMessages',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='newNotifications',
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
