# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-09 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0031_auto_20181109_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='subject', max_length=40),
            preserve_default=False,
        ),
    ]
