# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-09 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0032_message_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
