# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-14 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0038_auto_20181109_2349'),
        ('UrTourn', '0031_auto_20181114_2146'),
    ]

    operations = [
    ]
