# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-27 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0040_auto_20181119_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, upload_to='messages/'),
        ),
    ]
