# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-30 16:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UrTourn', '0041_auto_20181127_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='date',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='Subject', max_length=40),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 30, 16, 33, 49, 748672, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 11, 30, 16, 34, 1, 662431, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
