# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-01 03:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0041_auto_20181127_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='date',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 12, 1, 3, 14, 9, 800010, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
