# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-30 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UrTourn', '0042_auto_20181130_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='likes',
        ),
    ]
